'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34003
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBP.installer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;data:text/html,&lt;html&gt;&lt;head&gt;&lt;title&gt;VBPUpload&lt;/title&gt;&lt;/head&gt;&lt;body style=\&quot;font-family: Segoe UI;\&quot;&gt;&lt;img src=\&quot;http://s7.directupload.net/images/131127/k4otdaef.png\&quot; alt=\&quot;\&quot; style=\&quot;position: fixed; top: 0px; right: 0px;\&quot; /&gt;&lt;h1 style=\&quot;text-align: center; margin-top: 40px; margin-bottom: 30px; color: green\&quot;&gt;&amp;#x2713; Fast fertig!&lt;/h1&gt;&lt;hr /&gt;&lt;b&gt;Bitte gehen Sie wie folgt vor, um die Chrome-Erweiterung zu aktivieren:&lt;/b&gt;&lt;ol&gt;&lt;li&gt;Klicken Sie auf &lt;i&gt;Google Chrome anpassen und einstellen&lt;/i&gt; (am Pfeil).&lt;/li&gt;&lt;li&gt;Kl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property chrome() As String
            Get
                Return ResourceManager.GetString("chrome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   {{
        '''    &quot;external_crx&quot;: &quot;{0}&quot;,
        '''    &quot;external_version&quot;: &quot;1.0&quot;
        '''  }} ähnelt.
        '''</summary>
        Friend ReadOnly Property json() As String
            Get
                Return ResourceManager.GetString("json", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property VBP() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBP", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property VBP_connect() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBP_connect", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property VBP_extension() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("VBP_extension", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
